import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import Calculator from "./Calculator";
import XSSComponent from "./XSSComponent";
import EvalComponent from "./EvalComponent";
import SecretComponent from "./SecretComponent";
import SQLInjectionComponent from "./SQLInjectionComponent";
import UnsafeHandler from "./UnsafeHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Code QL Software Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`container-fluid ${geistSans.variable} ${geistMono.variable} py-4`}
      >
        <div className="row">
          <div className="col-12 col-lg-7">
            <Calculator />
          </div>
          <div className="col-12 col-lg-3">
            <div className="card mb-3">
              <div className="card-body">
                <XSSComponent />
              </div>
            </div>
            <div className="card mb-3">
              <div className="card-body">
                <EvalComponent />
              </div>
            </div>
            <div className="card mb-3">
              <div className="card-body">
                <SecretComponent />
              </div>
            </div>
            <div className="card mb-3">
              <div className="card-body">
                <SQLInjectionComponent />
              </div>
            </div>
            <div className="card">
              <div className="card-body">
                <UnsafeHandler />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
